---
galaxy_info:
  author: SÃ©bastien Nicaise
  description: Ansible Playbook to install cd-pricing.
  license: MIT
  min_ansible_version: 1.9
  platforms:
  - name: Ubuntu
    versions:
    - trusty
  categories:
  - development
dependencies:
  - { role: java }
